sample-sheet: 'samples.tsv'
project: '211112_A01093_0063_AHMFWVDRXY'
remote:
  location: 'ngs-cli'
ref:
  genome: 'library/human_g1k_v37_decoy.fasta'
  genome2: 'library/human_g1k_v37.fasta'
  dbsnp: 'library/dbsnp_138.b37.vcf'
  clinvar: 'library/clinvar.vcf.gz'
  known-variants: 
    - 'library/Mills_and_1000G_gold_standard.indels.b37.vcf'
    - 'library/1000G_phase1.indels.b37.vcf'
  1kg-variants: 'library/SureSelect_1KG_phase_1-22_SNPS.vcf'
  bait-region: 'library/Twist_Exome_Core_RefSeq_Targets_b37_decoy.interval_list'
  target-region: 'library/ccds.interval_list'
  exons: 'library/all_refseq_exons_ip_12.bed'
  giab: 'library/GIAB.NIST.hc.snps.indels.chr22.vcf.gz'
  mos: 'library/split_merge.txt'
  gnomad-af: 'library/gnomad.genomes.r2.1.1.sites.pass.freqs.nochr.vcf.gz'
gatk4: '/daten/cuba/Conda/Environments/gatk_4.1.3/bin/gatk'
fastqscreen: 'library/fastq_screen.conf'
bins: 20
output-extensions:
  single:
    - 'bam'
    - 'bai'
    - 'bam.md5'
    - 'vcf.gz'
    - 'vcf.gz.tbi'
  family:
    - 'vcf.gz'
    - 'vcf.gz.tbi'
    - 'ped'
